-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title text,
  url text,
  description text,
  rating numeric, 
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, url, description, rating)
values
  ('Thinkful', 'https://www.thinkful.com', 'Think outside the classroom', 5),
  ('Google', 'https://www.google.com', 'Google it', 4),
  ('MDN', 'https://developer.mozilla.org', 'stack overflow but not', 3)
  ('Discord', 'https://discordapp.com/', 'chat with friends while you game', 5),
  ('Facebook', 'https://www.facebook.com', 'give away your data for free to a company that makes millions on it', 1),
  ('The Fantasy Footballers', 'https://thefantasyfootballers.com', 'fantasy football advice podcast',5),
  ('Nexus Mods', 'https://www.nexusmods.com/', 'where you go to mod skyrim', 4),
  ('Reddit', 'https://www.reddit.com/', 'the front page of the internet', 3),
  ('Fox News', 'https://www.foxnews.com/', 'where facts go to die', 1),
  ('Code.org', 'https://studio.code.org/home', 'A half baked way to learn coding',2);
